// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDictEntry(arg1, arg2) {
  return window['go']['main']['App']['AddDictEntry'](arg1, arg2);
}

export function CheckFolder(arg1) {
  return window['go']['main']['App']['CheckFolder'](arg1);
}

export function GetBatchStatus() {
  return window['go']['main']['App']['GetBatchStatus']();
}

export function GetBridgeStatus() {
  return window['go']['main']['App']['GetBridgeStatus']();
}

export function GetDictionary() {
  return window['go']['main']['App']['GetDictionary']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetScraperPresets() {
  return window['go']['main']['App']['GetScraperPresets']();
}

export function GetScraperStatus() {
  return window['go']['main']['App']['GetScraperStatus']();
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function SaveDictionary(arg1) {
  return window['go']['main']['App']['SaveDictionary'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartBatch(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartBatch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StartScraper(arg1) {
  return window['go']['main']['App']['StartScraper'](arg1);
}

export function StopBatch() {
  return window['go']['main']['App']['StopBatch']();
}

export function StopScraper() {
  return window['go']['main']['App']['StopScraper']();
}

export function TestScrapeChapter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestScrapeChapter'](arg1, arg2, arg3, arg4, arg5);
}

export function TranslateText(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TranslateText'](arg1, arg2, arg3, arg4, arg5);
}
