// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDictEntry(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CheckFolder(arg1:string):Promise<Record<string, any>>;

export function GetBatchStatus():Promise<Record<string, any>>;

export function GetBridgeStatus():Promise<Record<string, any>>;

export function GetDictionary():Promise<Record<string, any>>;

export function GetModels():Promise<Record<string, any>>;

export function GetScraperPresets():Promise<Record<string, any>>;

export function GetScraperStatus():Promise<Record<string, any>>;

export function LoadModel(arg1:string):Promise<Record<string, any>>;

export function SaveDictionary(arg1:string):Promise<Record<string, any>>;

export function SelectFolder():Promise<string>;

export function StartBatch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:boolean):Promise<Record<string, any>>;

export function StartScraper(arg1:Record<string, any>):Promise<Record<string, any>>;

export function StopBatch():Promise<Record<string, any>>;

export function StopScraper():Promise<Record<string, any>>;

export function TestScrapeChapter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;

export function TranslateText(arg1:string,arg2:string,arg3:number,arg4:number,arg5:boolean):Promise<Record<string, any>>;
